---
# vars file for openshift-origin-client-tools
oc_name: 'openshift-origin-client-tools-{{ oc_ver }}-{{ oc_sha }}-{{ oc_platform }}'
oc_filename: '{{ oc_name }}.{{ oc_download_format|default("tar.gz") }}'

# https://github.com/openshift/origin/releases/download/v3.10.0/openshift-origin-client-tools-v3.10.0-dd10d17-linux-64bit.tar.gz
oc_download_url: '{{ oc_mirror }}/{{ oc_ver }}/{{ oc_filename }}'
oc_checksum: '{{ oc_checksums[oc_ver][oc_sha][oc_platform] }}'

oc_unarchive_dir: '{{ oc_install_parent_dir }}'

# /usr/local/bin/openshift-origin-client-tools-v3.10.0-dd10d17-linux-64bit/
oc_install_dir: '{{ oc_install_parent_dir }}/{{ oc_name }}'
