{{- if gt (len .Values.externalServices.jenkins.environments) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-jenkins-credentials
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: jenkins-credentials
type: Opaque
data:
  {{- range $index, $env := .Values.externalServices.jenkins.environments }}
  JENKINS_{{ $env.name | upper | replace "-" "_" }}_API_TOKEN: {{ $env.apiToken | b64enc | quote }}
  {{- end }}
{{- end }}
