apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: {{ .Values.global.appName }}
  name: {{ .Values.global.appName }}
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: {{ printf "%s:%s" .Values.global.appName .Values.global.odsImageTag }}
  postCommit: {}
  resources:
    limits:
      cpu: {{ .Values.buildConfig.cpuLimit }}
      memory: {{ .Values.buildConfig.memLimit }}
    requests:
      cpu: {{ .Values.buildConfig.cpuRequest }}
      memory: {{ .Values.buildConfig.memRequest }}
  runPolicy: Serial
  source:
    contextDir: sonarqube/docker
    git:
      uri: {{ .Values.global.repoBase }}/{{ .Values.global.odsBitBucketProject }}/ods-core.git
      ref: {{ .Values.global.odsGitRef }}
    sourceSecret:
      name: cd-user-token
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: sonarqube:{{ .Values.global.sonarVersion }}-{{ .Values.global.sonarEdition }}
      forcePull: true
      noCache: true
      buildArgs:
        - name: sonarVersion
          value: {{ .Values.global.sonarVersion }}
        - name: APP_DNS
          value: {{ .Values.global.appDNS }}
        - name: sonarEdition
          value:  {{ .Values.global.sonarEdition }}
  successfulBuildsHistoryLimit: 5