apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: {{ .Values.global.sonarqubeFastStorageProvisioner }}
    helm.sh/resource-policy: keep
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: {{ .Values.global.appName }}
  name: {{ .Values.global.sonarqubeDataStorageName }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sonarqube.pvcDataCapacity }}
  storageClassName: {{ .Values.global.sonarqubeFastStorageClassData }}
  volumeMode: Filesystem
