{{- if .Values.externalServices.uipath.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-uipath-credentials
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: uipath-credentials
type: Opaque
data:
  UIPATH_CLIENT_ID: {{ .Values.externalServices.uipath.clientId | b64enc | quote }}
  UIPATH_CLIENT_SECRET: {{ .Values.externalServices.uipath.clientSecret | b64enc | quote }}
  {{- if .Values.externalServices.uipath.ssl.trustStorePassword }}
  UIPATH_SSL_TRUSTSTORE_PASSWORD: {{ .Values.externalServices.uipath.ssl.trustStorePassword | b64enc | quote }}
  {{- end }}
{{- end }}
