{{- if gt (len .Values.externalServices.openshift.instances) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-openshift-credentials
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: openshift-credentials
type: Opaque
data:
  {{- range $index, $instance := .Values.externalServices.openshift.instances }}
  OPENSHIFT_{{ $instance.name | upper | replace "-" "_" }}_TOKEN: {{ $instance.token | b64enc | quote }}
  {{- end }}
{{- end }}
