{{- if .Values.apis.projectUsers.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-project-users-credentials
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: project-users-credentials
type: Opaque
data:
  API_PROJECT_USERS_TOKEN_SECRET: {{ .Values.apis.projectUsers.token.secret | b64enc | quote }}
{{- end }}
