{{- if .Values.externalServices.aap.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-aap-credentials
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: aap-credentials
type: Opaque
data:
  ANSIBLE_USERNAME: {{ .Values.externalServices.aap.username | b64enc | quote }}
  ANSIBLE_PASSWORD: {{ .Values.externalServices.aap.password | b64enc | quote }}
  {{- if .Values.externalServices.aap.ssl.trustStorePassword }}
  ANSIBLE_SSL_TRUSTSTORE_PASSWORD: {{ .Values.externalServices.aap.ssl.trustStorePassword | b64enc | quote }}
  {{- end }}
{{- end }}
