---

galaxy_info:
    author: srsp
    description: Oracle JDK 8/9/10 for CentOS/Debian/Ubuntu/Suse/MacOSX
    license: Apache

    min_ansible_version: 2.0.0

    platforms:
        - name: Ubuntu
          versions:
              - precise
              - trusty
              - xenial
              - yakkety
              - zesty
        - name: Debian
          versions:
              - wheezy
              - jessie
              - stretch
        - name: EL
          versions:
              - 6
              - 7
        - name: opensuse
          versions:
              - all
        - name: SLES
          versions:
              - all
        - name: Darwin
          versions:
              - all

    galaxy_tags:
        - oracle
        - java
        - java development
        - jdk
        - jdk8
        - jdk9
        - jdk10
        - jvm
        - jce
        - development
        - system

dependencies: []
