# set atlassian versions
atlassian_crowd_version: 3.4.4
atlassian_bitbucket_version: 5.16.3
atlassian_jira_version: 7.13.3
atlassian_confluence_version: 6.14.3
git_version: 2.19.1
tailor_version: 1.0.0
