---

#
# variables needed to be defined in user's playbook
#



#
# user-configurable defaults
#

java_version: 8
java_subversion: 172

java_download_path: /tmp
java_download_from_oracle: true
java_remove_download: true
java_install_jce: false
java_mirror: http://download.oracle.com/otn-pub/java

java_set_javahome: false
