{{- if .Values.externalServices.projectsInfoService.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-projects-info-service-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: projects-info-service-config
data:
  PROJECTS_INFO_SERVICE_BASE_URL: {{ .Values.externalServices.projectsInfoService.baseUrl | quote }}
{{- end }}
