{{- if .Values.externalServices.projectsInfoService.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-projects-info-service-credentials
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: projects-info-service-credentials
type: Opaque
data:
  {{- if .Values.externalServices.projectsInfoService.ssl.trustStorePassword }}
  PROJECTS_INFO_SERVICE_SSL_TRUSTSTORE_PASSWORD: {{ .Values.externalServices.projectsInfoService.ssl.trustStorePassword | b64enc | quote }}
  {{- end }}
  PROJECTS_INFO_SERVICE_AZURE_ACCESS_TOKEN: {{ .Values.externalServices.projectsInfoService.azure.accessToken | b64enc | quote }}
  PROJECTS_INFO_SERVICE_TESTING_HUB_API_TOKEN: {{ .Values.externalServices.projectsInfoService.testingHub.api.token | b64enc | quote }}
  PROJECTS_INFO_SERVICE_OPENSHIFT_US_TEST_TOKEN: {{ .Values.externalServices.projectsInfoService.openshift.api.clusters.usTest.token | b64enc | quote }}
  PROJECTS_INFO_SERVICE_OPENSHIFT_EU_DEV_TOKEN: {{ .Values.externalServices.projectsInfoService.openshift.api.clusters.euDev.token | b64enc | quote }}
  PROJECTS_INFO_SERVICE_OPENSHIFT_US_DEV_TOKEN: {{ .Values.externalServices.projectsInfoService.openshift.api.clusters.usDev.token | b64enc | quote }}
  PROJECTS_INFO_SERVICE_OPENSHIFT_CN_DEV_TOKEN: {{ .Values.externalServices.projectsInfoService.openshift.api.clusters.cnDev.token | b64enc | quote }}
  PROJECTS_INFO_SERVICE_OPENSHIFT_INH_DEV_TOKEN: {{ .Values.externalServices.projectsInfoService.openshift.api.clusters.inhDev.token | b64enc | quote }}
  PROJECTS_INFO_SERVICE_PLATFORMS_BEARER_TOKEN: {{ .Values.externalServices.projectsInfoService.platforms.bearer.token | b64enc | quote }}
{{- end }}

