---
- hosts: "{{ test_hosts|default('all') }}"
  become: yes
  become_method: sudo
  tasks:
    - include: 'tasks/main.yml'

  # vars from defaults/main.yml
  vars:
    java_version: 9
    java_subversion: 0.4

    java_download_path: /tmp
    java_download_from_oracle: true
    java_remove_download: false
    java_install_jce: false
    java_mirror: http://download.oracle.com/otn-pub/java

    java_set_javahome: false
